apiVersion: apps/v1
kind: Deployment
metadata:
  name: bhanuteja822-deployment
  namespace: nv1
  labels:
    app: new-docker-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: new-docker-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: new-docker-app
    spec:
      initContainers:
      - name: init-setup
        image: busybox:latest
        command: ['sh', '-c', 'ls; pwd; sleep 10']
        envFrom:
        - configMapRef:
            name: new-docker-app-deployment
      containers:
      - name: new-docker-app
        image: hello12345.azurecr.io/bhanuteja822:latest  # Use your custom Docker image here
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /_status/healthz
            port: 5000
          initialDelaySeconds: 8
          periodSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /readiness
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 5
        env:
        - name: new-docker-app-deployment
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: new-docker-app-deployment
